# Generated by Django 4.1.4 on 2023-01-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_contact_rename_deals_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='latName',
            new_name='lastName',
        ),
    ]
